import { Navigation } from '@/components/Header/Navigation'
import { StateContext } from '@/lib/context'

import '@/styles/scss/global.scss'
import { Roboto } from '@next/font/google'
import type { AppProps } from 'next/app'
import Head from 'next/head'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <StateContext>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        <Navigation />
        <Component {...pageProps} />
      </div>
    </StateContext>
  )
}
